### ISSUE TITLE
Missing filebeat-syslog directory, however it is referred in docker-composer.yml file

### ISSUE THREAD

**Issue by liu-xiao-guo** [xeraa/java-logging#23]
filebeat-syslog directory is used in the following, but it is missing in the repository:

 filebeat_syslog:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_STACK_VERSION}
    hostname: filebeat_syslog
    container_name: filebeat_syslog
    command: filebeat -e
    restart: on-failure
    volumes:
      # Bind-mount a custom configuration file
      - "./docker-compose/filebeat-syslog.yml:/usr/share/filebeat/filebeat.yml:ro"
      # Bind-mount the config directory so it can be dynamically loaded
      - "./docker-compose/filebeat-syslog/config/:/usr/share/filebeat/config/:ro"
      # Bind-mount the registry file to avoid data duplication between restarts
      - "./docker-compose/filebeat-syslog/registry/:/usr/share/filebeat/data/"
    networks:
      - stack
    depends_on:
      - elasticsearch

**Comment by xeraa** [comment]
Thanks! Most of them will be generated and are required, but `./docker-compose/filebeat-syslog/config/` is really unused.
